//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactID { get; set; }
        public int ObjectTypeID { get; set; }
        public int ObjectID { get; set; }
        public int ContactTypeID { get; set; }
        public string Value { get; set; }
        public string Details { get; set; }
        public bool IsMain { get; set; }
    
        public virtual Sys_ContactTypes Sys_ContactTypes { get; set; }
        public virtual Sys_ObjectTypes Sys_ObjectTypes { get; set; }
    }
}
