//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverLicens
    {
        public int DriverID { get; set; }
        public string LicenseTypeID { get; set; }
        public Nullable<System.DateTime> LicenseFromDate { get; set; }
        public Nullable<System.DateTime> LicenseValidDate { get; set; }
        public string LicenseTypeDetails { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
