//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.DriverLicenses = new HashSet<DriverLicens>();
            this.Vehicles = new HashSet<Vehicle>();
            this.LineSchedules = new HashSet<LineSchedule>();
        }
    
        public int DriverID { get; set; }
        public int CompanyID { get; set; }
        public string DriverLicenseID { get; set; }
        public string LicenseDetails { get; set; }
        public int ObjectTypeGroupID { get; set; }
        public Nullable<int> DFVehicleID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverLicens> DriverLicenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual ObjectTypeGroup ObjectTypeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineSchedule> LineSchedules { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
