//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LineRoute()
        {
            this.Passengers = new HashSet<Passenger>();
        }
    
        public int LineRouteID { get; set; }
        public int LineID { get; set; }
        public int LocationIndex { get; set; }
        public decimal LatNCrdnt { get; set; }
        public decimal LongECrdnt { get; set; }
        public string Description { get; set; }
        public System.TimeSpan EstimatedLineTime { get; set; }
        public Nullable<int> LineServiceID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Line Line { get; set; }
        public virtual LineService LineService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger> Passengers { get; set; }
    }
}
