//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Line()
        {
            this.LineObjects = new HashSet<LineObject>();
            this.LineRoutes = new HashSet<LineRoute>();
            this.LineServices = new HashSet<LineService>();
            this.ServiceTariffs = new HashSet<ServiceTariff>();
        }
    
        public int LineID { get; set; }
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public bool IsTravelRepeat { get; set; }
        public Nullable<int> RideTypeID { get; set; }
        public int VehicleTypeID { get; set; }
        public int LineAccessKeyID { get; set; }
        public string SerialNo { get; set; }
        public string LineNumber { get; set; }
        public string LineDetails { get; set; }
        public string CustomerOfficialDesc { get; set; }
        public string LineNum { get; set; }
        public string Reference { get; set; }
        public string CostingCenter { get; set; }
        public long TotalEstimatedMinutes { get; set; }
        public decimal TotalEstimatedDistance { get; set; }
        public decimal TotalSupplierPrice { get; set; }
        public decimal TotalCustomerPrice { get; set; }
        public string LineInstructions { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineObject> LineObjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineRoute> LineRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineService> LineServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceTariff> ServiceTariffs { get; set; }
        public virtual Sys_VehicleTypes Sys_VehicleTypes { get; set; }
        public virtual Sys_LineAccesskeys Sys_LineAccesskeys { get; set; }
        public virtual Sys_RideTypes Sys_RideTypes { get; set; }
    }
}
