//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RideService()
        {
            this.RideRoutes = new HashSet<RideRoute>();
            this.RideServiceObjectPrices = new HashSet<RideServiceObjectPrice>();
        }
    
        public int RideServiceID { get; set; }
        public int RideID { get; set; }
        public int ServiceID { get; set; }
        public string FromServiceUnit { get; set; }
        public string ToServiceUnit { get; set; }
        public Nullable<double> ServiceUnitQuantity { get; set; }
        public string ServiceDetails { get; set; }
        public int DebitPriceID { get; set; }
        public decimal DebitPrice { get; set; }
        public Nullable<int> CreditPriceID { get; set; }
        public decimal CreditPrice { get; set; }
        public string ReferenceNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideRoute> RideRoutes { get; set; }
        public virtual Ride Ride { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideServiceObjectPrice> RideServiceObjectPrices { get; set; }
        public virtual ServiceTariff ServiceTariff { get; set; }
        public virtual ServiceTariff ServiceTariff1 { get; set; }
        public virtual Sys_Services Sys_Services { get; set; }
    }
}
