//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideStatus
    {
        public int RideID { get; set; }
        public int CompanyID { get; set; }
        public int StatusID { get; set; }
        public string StatusDesc { get; set; }
        public Nullable<System.DateTime> RideStatusDT { get; set; }
    
        public virtual Ride Ride { get; set; }
        public virtual Sys_RideStatuses Sys_RideStatuses { get; set; }
    }
}
