//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RideObject()
        {
            this.RideServiceObjectPrices = new HashSet<RideServiceObjectPrice>();
        }
    
        public int RideObjectID { get; set; }
        public int RideID { get; set; }
        public int ObjectTypeID { get; set; }
        public string ObjectID { get; set; }
    
        public virtual Ride Ride { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideServiceObjectPrice> RideServiceObjectPrices { get; set; }
        public virtual Sys_ObjectTypes Sys_ObjectTypes { get; set; }
    }
}
