//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ride
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ride()
        {
            this.RideObjects = new HashSet<RideObject>();
            this.RideRoutes = new HashSet<RideRoute>();
            this.RideServiceObjectPrices = new HashSet<RideServiceObjectPrice>();
            this.RideServices = new HashSet<RideService>();
            this.RideStatuses = new HashSet<RideStatus>();
        }
    
        public int RideID { get; set; }
        public Nullable<int> RidePlannedID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string RideName { get; set; }
        public int RideTypeID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public System.TimeSpan ToTime { get; set; }
        public Nullable<long> TotalEstimatedMinutes { get; set; }
        public Nullable<decimal> TotalEstimatedDistance { get; set; }
        public string RideInstructions { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideObject> RideObjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideRoute> RideRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideServiceObjectPrice> RideServiceObjectPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideService> RideServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideStatus> RideStatuses { get; set; }
    }
}
