//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTariff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceTariff()
        {
            this.RideServices = new HashSet<RideService>();
            this.RideServices1 = new HashSet<RideService>();
        }
    
        public int ServiceTariffID { get; set; }
        public int LineID { get; set; }
        public int RideTypeServiceID { get; set; }
        public int ObjectTypeID { get; set; }
        public string ObjectID { get; set; }
        public System.DateTime FromDate { get; set; }
        public decimal Price { get; set; }
    
        public virtual Line Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideService> RideServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideService> RideServices1 { get; set; }
        public virtual RideTypeService RideTypeService { get; set; }
        public virtual Sys_ObjectTypes Sys_ObjectTypes { get; set; }
    }
}
