//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Services()
        {
            this.LineServices = new HashSet<LineService>();
            this.RideServices = new HashSet<RideService>();
            this.RideTypeServices = new HashSet<RideTypeService>();
        }
    
        public int ServiceID { get; set; }
        public string ServiceDesc { get; set; }
        public string OfficialDescription { get; set; }
        public int UnitID { get; set; }
        public Nullable<bool> IsHours { get; set; }
        public Nullable<bool> IsDistance { get; set; }
        public Nullable<bool> IsLocation { get; set; }
        public Nullable<int> DebtObjectTypeID { get; set; }
        public Nullable<double> DebtPercentage { get; set; }
        public Nullable<int> CreditObjectTypeID { get; set; }
        public Nullable<double> CreditPercentage { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsAddition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineService> LineServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideService> RideServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RideTypeService> RideTypeServices { get; set; }
        public virtual Sys_ObjectTypes Sys_ObjectTypes { get; set; }
        public virtual Sys_ObjectTypes Sys_ObjectTypes1 { get; set; }
        public virtual Sys_Units Sys_Units { get; set; }
    }
}
