//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Units
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Units()
        {
            this.LineServices = new HashSet<LineService>();
            this.Sys_Services = new HashSet<Sys_Services>();
        }
    
        public int UnitID { get; set; }
        public int UnitGroupID { get; set; }
        public string UnitDesc { get; set; }
        public bool IsBaseUnit { get; set; }
        public Nullable<decimal> ConvertToBaseFactor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineService> LineServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Services> Sys_Services { get; set; }
        public virtual Sys_UnitGroups Sys_UnitGroups { get; set; }
    }
}
