//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Hazmanot
    {
        public int MisparHazmana { get; set; }
        public string TaarichHazmana { get; set; }
        public int MisparLakoah { get; set; }
        public string ShemLakoah { get; set; }
        public string KtovetLakoah { get; set; }
        public string Mazmin { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string MakorHazmana { get; set; }
        public string TeurHazmana { get; set; }
        public string TaarichHathala { get; set; }
        public string TaarichSiyum { get; set; }
        public string MakomHathala { get; set; }
        public string MakomSiyum { get; set; }
        public string ShaatHathala { get; set; }
        public string ShaatSiyum { get; set; }
        public string Pratim { get; set; }
        public decimal SHKMerhak { get; set; }
        public decimal SHKZman { get; set; }
        public decimal SHKBeynayim { get; set; }
        public decimal AhusHanaha { get; set; }
        public decimal SchumHanaha { get; set; }
        public Nullable<decimal> AhreyHanaha { get; set; }
        public decimal AhusMaam { get; set; }
        public decimal SchumMaam { get; set; }
        public decimal SHKLeMismach { get; set; }
        public short KodMatbea { get; set; }
        public string TaarichShiaruch { get; set; }
        public short KodTnayTashlum { get; set; }
        public byte KodEmzaiTashlum { get; set; }
        public long MisparKartisAshray { get; set; }
        public string TokefAshray { get; set; }
        public long MisparTZ { get; set; }
        public string ShemBaalimAshray { get; set; }
        public byte MisparTashlumim { get; set; }
        public string LeTashlumMeTaarich { get; set; }
        public string LeTashlumAdTaarich { get; set; }
        public string Hearot { get; set; }
        public short KodStatusHazmana { get; set; }
        public string TaarichStatus { get; set; }
        public bool IsPail { get; set; }
        public long ShotefNesia { get; set; }
        public string NiftahAY { get; set; }
        public string TaarichPtiha { get; set; }
        public string UdkanAY { get; set; }
        public string TaarichIdkun { get; set; }
        public short Shana { get; set; }
        public string Email { get; set; }
        public short KodSnifMazmin { get; set; }
        public string SimuchinLakoah { get; set; }
        public string MerkazTamhir { get; set; }
        public string IshKesherShem { get; set; }
        public string IsKesherTel { get; set; }
    }
}
