//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Lakohot
    {
        public int MisparLakoah { get; set; }
        public string ShemLakoah { get; set; }
        public string ShemMkuzar { get; set; }
        public string ShemIshKesher { get; set; }
        public short KodKvuzotLakohot { get; set; }
        public decimal AhusHanahaKvuaa { get; set; }
        public string ShitatHanahatLakoah { get; set; }
        public short KodMatbeaHazmada { get; set; }
        public short KodTnayTashlum { get; set; }
        public bool IsHayavMaam { get; set; }
        public int MisparKartisAv { get; set; }
        public string MisparHH { get; set; }
        public decimal SchumObligoMerabi { get; set; }
        public decimal SchumHazmanaMerabi { get; set; }
        public string MisparMahoz { get; set; }
        public string ShemMahoz { get; set; }
        public long MisparHoze { get; set; }
        public byte KodSherut { get; set; }
        public short Zeva { get; set; }
        public byte KodLuahShana { get; set; }
        public string Tmuna { get; set; }
        public bool IsPail { get; set; }
        public string NiftahAY { get; set; }
        public string TaarichPtiha { get; set; }
        public string UdkanAY { get; set; }
        public string TaarichIdkun { get; set; }
        public string ShemPrati { get; set; }
        public string MazavMishpahti { get; set; }
        public string TaarichLeyda { get; set; }
        public short KodMaamad { get; set; }
        public short KodMahala { get; set; }
        public short KodMigbala { get; set; }
        public short KodSugEzra { get; set; }
        public short KodKH { get; set; }
        public bool IsIshurKH { get; set; }
        public bool IsHatimatHole { get; set; }
        public bool IsHeshbonitLefiLakoahAv { get; set; }
        public string SimuchinLakoah { get; set; }
        public int KodMosad { get; set; }
        public int TaarichIshurKH { get; set; }
        public string TaarichHatimatHole { get; set; }
        public string SugMezahe { get; set; }
        public string Mezahe { get; set; }
        public bool IsAdifut { get; set; }
        public string GoremMeasher { get; set; }
        public byte Adifut { get; set; }
    }
}
