//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Nesiot
    {
        public long ShotefNesia { get; set; }
        public string Taarich { get; set; }
        public int MisparLakoah { get; set; }
        public string ShemLakoah { get; set; }
        public int MisparMaslul { get; set; }
        public int ShotefMaslul { get; set; }
        public int KodMoza { get; set; }
        public int KodDerech { get; set; }
        public int KodYaad { get; set; }
        public string TeurNesia { get; set; }
        public string ShemMkuzar { get; set; }
        public short KodSugNesia { get; set; }
        public short KodSugRechev { get; set; }
        public short KamutNoseim { get; set; }
        public int MisparNehag { get; set; }
        public int MisparRechev { get; set; }
        public decimal Merhak { get; set; }
        public string MeShaa { get; set; }
        public string AdShaa { get; set; }
        public decimal Zman { get; set; }
        public decimal ZmanKodemLeHityazvut { get; set; }
        public decimal Kamut { get; set; }
        public bool IsMaslulMishni { get; set; }
        public short KodMatbea { get; set; }
        public string TaarichErech { get; set; }
        public decimal MehirA { get; set; }
        public short KodMatbeaMehirA { get; set; }
        public decimal MehirMeshuarachA { get; set; }
        public decimal MehirB { get; set; }
        public short KodMatbeaMehirB { get; set; }
        public decimal MehirMeshuarachB { get; set; }
        public decimal MehirC { get; set; }
        public short KodMatbeaMehirC { get; set; }
        public decimal MehirMeshuarachC { get; set; }
        public decimal MehirD { get; set; }
        public short KodMatbeaMehirD { get; set; }
        public decimal MehirMeshuarachD { get; set; }
        public decimal MehirE { get; set; }
        public short KodMatbeaMehirE { get; set; }
        public decimal MehirMeshuarachE { get; set; }
        public string TaarichIdkunMehirim { get; set; }
        public string MisparKavLakoah { get; set; }
        public string SugReshumatMakor { get; set; }
        public long ShotefReshumatMakor { get; set; }
        public short MSDReshumatMakor { get; set; }
        public short MisparKvuza { get; set; }
        public short MisparKavPnimi { get; set; }
        public short KodStatusLakoah { get; set; }
        public string TaarichStatusLakoah { get; set; }
        public short KodStatusNehag { get; set; }
        public string TaarichStatusNehag { get; set; }
        public int KMBeHityazvutBePratim { get; set; }
        public int KMGmarBePratim { get; set; }
        public decimal MerhakBePratim { get; set; }
        public decimal KMBePratim { get; set; }
        public string ShaatHityazbutBePratim { get; set; }
        public string ShaatGmarBePratim { get; set; }
        public decimal ZmanBePratim { get; set; }
        public decimal ShaotNosafotBePratim { get; set; }
        public decimal BeynayimBePratim { get; set; }
        public decimal MaamBePratim { get; set; }
        public decimal SHKBePratim { get; set; }
        public string SugNigreretSA { get; set; }
        public bool IsLeHazigBeSA { get; set; }
        public bool IsPail { get; set; }
        public string NiftahAY { get; set; }
        public string TaarichPtiha { get; set; }
        public string UdkanAY { get; set; }
        public string TaarichIdkun { get; set; }
        public short Shana { get; set; }
        public string ShaaLeHityatzvut { get; set; }
        public bool IsIshurKH { get; set; }
        public short KodSnifMazmin { get; set; }
        public string ShaaMekorit { get; set; }
        public string SimuchinLakoah { get; set; }
        public string MerkazTamhir { get; set; }
        public bool IsKvishAgra { get; set; }
        public long ShotefNesiaMakor { get; set; }
        public string SugNesiaMakor { get; set; }
        public bool IsAdifut { get; set; }
        public byte Adifut { get; set; }
    }
}
