//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BForWebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Sapakim
    {
        public int MisparSapak { get; set; }
        public string ShemSapak { get; set; }
        public short KodKvuzotSapakim { get; set; }
        public string MisparHH { get; set; }
        public string TZHP { get; set; }
        public string ShemIshKesher { get; set; }
        public decimal AhuzHanahaKlali { get; set; }
        public decimal AhuzHanahatAvoda { get; set; }
        public decimal HanahaHalafim { get; set; }
        public decimal AhuzHanahaAmlatHuz { get; set; }
        public string TaarichPtiha { get; set; }
        public string NiftahAY { get; set; }
        public string TaarichIdkun { get; set; }
        public string UdkanAY { get; set; }
        public bool IsPail { get; set; }
    }
}
